{"timestamp": "2024-03-15T12:13:55.398613", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0003428459167480469", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "ab7d21e9-52c6-4f8c-9b24-c2aa92cfc0a5", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0004048347473144531, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T12:14:31.410655", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0003619194030761719", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "aaa7a162-79fa-4993-8a45-15cfb8a539a9", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"37454a07-87e4-4a99-a2df-012dd10cc868\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T12:14:31.410461\"}", "requestDuration": 0.0004208087921142578, "error": "{\"errorReference\": \"37454a07-87e4-4a99-a2df-012dd10cc868\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T12:14:31.410461\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:37:32.855640", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00028395652770996094", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "fa41b368-2b2d-4618-ac9d-b47837fa2237", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.00033211708068847656, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:44:25.330854", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0007338523864746094", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "d1f3d05b-e642-4957-87ee-ba5b8a54693a", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0008339881896972656, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:44:50.169806", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0003058910369873047", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "b1f71fba-8f33-486b-9315-0bc55638d5e6", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0003528594970703125, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:44:51.087991", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00011801719665527344", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "5486857a-ef28-4976-8837-5c180c3d1475", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0001499652862548828, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:45:19.941684", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0003299713134765625", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "a08661d8-8bfe-4568-9a79-837d0919ff9d", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0003829002380371094, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:45:20.692281", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0002040863037109375", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "dd5cfa44-f503-4f03-bc2e-9fb9adfb7377", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0002510547637939453, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:05.474323", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00039386749267578125", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "f81d35b6-c39e-4b3e-8d05-6c9b8f0f7c24", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0004677772521972656, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:06.037249", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00021505355834960938", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "201542f0-32b8-45b5-8811-52453dd1a500", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0002689361572265625, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:06.281281", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00021409988403320312", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "6c7c8e70-59ee-43ee-bba4-39c7b01ca772", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0002620220184326172, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:06.469490", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0002961158752441406", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "17a4f913-43ea-4af5-9e05-0618313f6f42", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0003509521484375, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:06.650838", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0002110004425048828", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "fdf2a6a4-f799-4139-bf4c-a960af0bcc72", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.00025916099548339844, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:06.838205", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00021505355834960938", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "20eef042-32c3-40cf-a13c-c21475de940d", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0002639293670654297, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:07.014112", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00010609626770019531", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "c842b06b-e035-4599-acd0-b935760f384e", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.00013017654418945312, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:07.183842", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00023031234741210938", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "939a53bc-234e-42ae-b2e0-1b37f9eb636a", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0002753734588623047, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:07.352638", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00018215179443359375", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "54de13e5-dd6f-40f0-922e-cfb6050b5bd9", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.00022101402282714844, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:46:40.271420", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00033092498779296875", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "35ad1eba-c431-4db5-b035-ab8b30a9c780", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"913a684a-36df-4d0a-9d39-697e1f26f663\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T13:46:40.271258\"}", "requestDuration": 0.0003819465637207031, "error": "{\"errorReference\": \"913a684a-36df-4d0a-9d39-697e1f26f663\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T13:46:40.271258\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:50:39.103796", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00036406517028808594", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "9fa1b29f-e861-46d4-a17e-dd965ecff601", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"e7c9cb05-82fc-4bba-9344-5736156cf59d\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T13:50:39.103601\"}", "requestDuration": 0.0004220008850097656, "error": "{\"errorReference\": \"e7c9cb05-82fc-4bba-9344-5736156cf59d\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T13:50:39.103601\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:54:50.257459", "level": "ERROR", "method": "GET", "status_code": "500", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00027108192443847656", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "7d35ab52-29e3-4cfa-83c9-cb67bd3bcc42", "responseHeaders": {}, "responseBody": "An error occurred while handling an error", "requestDuration": 0.0003230571746826172, "error": "An error occurred while handling an error", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T13:55:02.962992", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0006320476531982422", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "f36e83da-3942-49d2-9f74-052e07fb1a5d", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"069a67df-bf30-4e9f-806e-306602b44a4a\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T13:55:02.962639\"}", "requestDuration": 0.00074005126953125, "error": "{\"errorReference\": \"069a67df-bf30-4e9f-806e-306602b44a4a\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T13:55:02.962639\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T20:13:17.138867", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0009028911590576172", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "a990be52-b1b0-4d3f-a91a-9b144ae37852", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"0445a7d6-9e2a-4222-bb6f-341afe1372e4\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:17.138358\"}", "requestDuration": 0.0010159015655517578, "error": "{\"errorReference\": \"0445a7d6-9e2a-4222-bb6f-341afe1372e4\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:17.138358\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T20:13:19.394019", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00018787384033203125", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "3b88c972-69c9-433f-91bd-84f1fd675201", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"6699c302-4800-4cc6-86fc-59440631d0c9\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:19.393929\"}", "requestDuration": 0.00023889541625976562, "error": "{\"errorReference\": \"6699c302-4800-4cc6-86fc-59440631d0c9\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:19.393929\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T20:13:20.344108", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.00019097328186035156", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "4045ec73-e111-41a3-aacf-f563425b9348", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"bd6b93b7-e90e-4dc3-b474-6a076a3d802b\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:20.344020\"}", "requestDuration": 0.00023698806762695312, "error": "{\"errorReference\": \"bd6b93b7-e90e-4dc3-b474-6a076a3d802b\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:20.344020\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T20:13:22.009012", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/t/", "forwarded_for": "", "response_time": "0.0001938343048095703", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "9ddd6570-ffef-42fd-802f-7fdc025b57b1", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"8f1525bd-fc14-41ef-8ec2-ac3c57cd3cac\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:22.008926\"}", "requestDuration": 0.00024008750915527344, "error": "{\"errorReference\": \"8f1525bd-fc14-41ef-8ec2-ac3c57cd3cac\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /t not found\", \"errors\": [\"Resource not found: Requested URL /t not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T20:13:22.008926\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /t not found\n"}
{"timestamp": "2024-03-15T20:13:32.707973", "level": "INFO", "method": "GET", "status_code": "200", "path": "http://localhost:8000/", "forwarded_for": "", "response_time": "0.00023293495178222656", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "c5100d16-b5ab-4938-b463-3be89b14b6dc", "responseHeaders": {}, "responseBody": "{\"hello\":\"world\"}", "requestDuration": 0.00031495094299316406, "error": "", "stack": ""}
{"timestamp": "2024-03-15T23:25:32.203682", "level": "INFO", "method": "GET", "status_code": "200", "path": "http://localhost:8000/", "forwarded_for": "", "response_time": "0.0005500316619873047", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "sec-fetch-site": "none", "connection": "keep-alive", "upgrade-insecure-requests": "1", "sec-fetch-mode": "navigate", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15", "accept-language": "en-GB,en;q=0.9", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate"}, "requestQuery": [], "requestBody": "", "logId": "faedb9e3-dcca-4dae-b71b-40e23ef2409c", "responseHeaders": {}, "responseBody": "{\"hello\":\"world\"}", "requestDuration": 0.0006520748138427734, "error": "", "stack": ""}
{"timestamp": "2024-03-15T23:25:32.267896", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/apple-touch-icon-precomposed.png", "forwarded_for": "", "response_time": "0.00013399124145507812", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "accept": "*/*", "accept-language": "en-GB,en;q=0.9", "connection": "keep-alive", "accept-encoding": "gzip, deflate", "user-agent": "Safari/19616.2.9.11.7 CFNetwork/1485 Darwin/23.1.0"}, "requestQuery": [], "requestBody": "", "logId": "85e69496-b10b-4b75-806e-d82ee161ac03", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"b9418a54-71bd-4830-8ccb-850b3f4878fd\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /apple-touch-icon-precomposed.png not found\", \"errors\": [\"Resource not found: Requested URL /apple-touch-icon-precomposed.png not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T23:25:32.267835\"}", "requestDuration": 0.00015687942504882812, "error": "{\"errorReference\": \"b9418a54-71bd-4830-8ccb-850b3f4878fd\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /apple-touch-icon-precomposed.png not found\", \"errors\": [\"Resource not found: Requested URL /apple-touch-icon-precomposed.png not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T23:25:32.267835\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /apple-touch-icon-precomposed.png not found\n"}
{"timestamp": "2024-03-15T23:25:32.270243", "level": "ERROR", "method": "GET", "status_code": "404", "path": "http://localhost:8000/apple-touch-icon.png", "forwarded_for": "", "response_time": "7.700920104980469e-05", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "accept": "*/*", "accept-language": "en-GB,en;q=0.9", "connection": "keep-alive", "accept-encoding": "gzip, deflate", "user-agent": "Safari/19616.2.9.11.7 CFNetwork/1485 Darwin/23.1.0"}, "requestQuery": [], "requestBody": "", "logId": "4cd6a5d1-f335-4a08-a96f-bda640ae9025", "responseHeaders": {}, "responseBody": "{\"errorReference\": \"9faa0d8e-2323-429d-a57f-04795e28a95b\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /apple-touch-icon.png not found\", \"errors\": [\"Resource not found: Requested URL /apple-touch-icon.png not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T23:25:32.270206\"}", "requestDuration": 9.822845458984375e-05, "error": "{\"errorReference\": \"9faa0d8e-2323-429d-a57f-04795e28a95b\", \"errorType\": \"NOT_FOUND_ERROR\", \"message\": \"Resource not found: Requested URL /apple-touch-icon.png not found\", \"errors\": [\"Resource not found: Requested URL /apple-touch-icon.png not found\"], \"statusCode\": 404, \"timeStamp\": \"2024-03-15T23:25:32.270206\"}", "stack": "Traceback (most recent call last):\n  File \"handle_request\", line 39, in handle_request\n    Iterable,\n              \n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 75, in get\n    return self._get(path, method, host)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nkenchor/.pyenv/versions/3.11.8/lib/python3.11/site-packages/sanic/router.py\", line 40, in _get\n    raise NotFound(f\"Requested URL {e.path} not found\") from None\nsanic.exceptions.NotFound: Requested URL /apple-touch-icon.png not found\n"}
{"timestamp": "2024-03-15T23:27:24.581621", "level": "INFO", "method": "GET", "status_code": "200", "path": "http://localhost:8000/", "forwarded_for": "", "response_time": "0.00022292137145996094", "version": "1", "correlation_id": "", "app_name": "tapi-user-service", "application_host": "localhost:8000", "logger_name": "", "ip": "127.0.0.1", "computerName": "Nkenchors-MacBook-Pro.local", "requestHeaders": {"host": "localhost:8000", "user-agent": "insomnia/8.6.1", "accept": "*/*"}, "requestQuery": [], "requestBody": "", "logId": "28dfaf4e-2082-46ca-92c6-54ba4823eb82", "responseHeaders": {}, "responseBody": "{\"hello\":\"world\"}", "requestDuration": 0.0003268718719482422, "error": "", "stack": ""}
